AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: slackblast-build-template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  SlackToken:
    Description: Slack token that is passed by the bot
    Type: String
    Default: "123"
  SlackSigningSecret:
    Description: Auth token used to pass to the controller to get the commands
    Type: String
    Default: "123"
  SlackClientSecret:
    Description: Auth token used to pass to the controller to get the commands
    Type: String
    Default: "123"
  SlackOauthScopes:
    Description: Auth token used to pass to the controller to get the commands
    Type: String
    Default: "chat:write,chat:write.customize,chat:write.public,im:write,commands,team:read,users:read,channels:read,files:read,files:write"
  Stage:
    Description: Parameter for getting the deployment stage
    Type: String
    Default: staging
  DatabaseHost:
    Description: RDS Database Host
    Type: String
    Default: "123"
  DatabaseUser:
    Description: RDS Database User
    Type: String
    Default: "moneyball"
  DatabasePassword:
    Description: RDS Database Password
    Type: String
    Default: "123"
  DatabaseSchema:
    Description: RDS Database Schema
    Type: String
    Default: "slackblast"
  PasswordEncryptKey:
    Description: Hash encrypt key for decrypting email passwords
    Type: String
    Default: "123"
  StravaClientID:
    Description: Strava Client ID
    Type: String
    Default: "123"
  StravaClientSecret:
    Description: Strava Client Secret
    Type: String
    Default: "123"

Mappings:
  StagesMap:
    staging:
      SlackClientID: "3135457248691.4852586913543"
      SlackStateS3Bucket: "slack-state-bucket"
      SlackInstallS3Bucket: "slack-installation-bucket"
      KeepWarmName: "SlackblastKeepWarmTest"
    prod:
      SlackClientID: "3135457248691.3241841713426"
      SlackStateS3Bucket: "slack-state-bucket"
      SlackInstallS3Bucket: "slack-installation-bucket"
      KeepWarmName: "SlackblastKeepWarmProd"

Resources:
  SlackblastFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: slackblast/
      Handler: app.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AmazonS3FullAccess
        - AWSLambdaRole
        - AmazonEventBridgeFullAccess
      Timeout: 400
      Events:
        Slackblast:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slack/events
            Method: post
        SlackblastInstall:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slack/install
            Method: get
        SlackblastKeepWarm:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(5 minutes)"
            Name: !FindInMap
              - StagesMap
              - Ref: Stage
              - KeepWarmName
        StravaExchange:
          Type: Api
          Properties:
            Path: /exchange_token
            Method: get
      Environment:
        Variables:
          SLACK_BOT_TOKEN: !Ref SlackToken
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          ENV_SLACK_CLIENT_SECRET: !Ref SlackClientSecret
          ENV_SLACK_SCOPES: !Ref SlackOauthScopes
          DATABASE_HOST: !Ref DatabaseHost
          ADMIN_DATABASE_USER: !Ref DatabaseUser
          ADMIN_DATABASE_PASSWORD: !Ref DatabasePassword
          ADMIN_DATABASE_SCHEMA: !Ref DatabaseSchema
          PASSWORD_ENCRYPT_KEY: !Ref PasswordEncryptKey
          ENV_SLACK_CLIENT_ID: !FindInMap
            - StagesMap
            - Ref: Stage
            - SlackClientID
          ENV_SLACK_STATE_S3_BUCKET_NAME: !FindInMap
            - StagesMap
            - Ref: Stage
            - SlackStateS3Bucket
          ENV_SLACK_INSTALLATION_S3_BUCKET_NAME: !FindInMap
            - StagesMap
            - Ref: Stage
            - SlackInstallS3Bucket
          STRAVA_CLIENT_ID: !Ref StravaClientID
          STRAVA_CLIENT_SECRET: !Ref StravaClientSecret

  # EventRule:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     Description: Keep the slackblast Lambda warm
  #     EventBusName: default
  #     Name: slackblast-warm
  #     ScheduleExpression: rate(5 minutes)
  #     State: ENABLED
  #     Targets:
  #       - Id: 'slackblast-warm'
  #         Arn: !GetAtt SlackblastFunction.Arn
  # S3Bucket:
  #   Type: AWS::S3::Bucket

  # ApplicationResourceGroup:
  #   Type: AWS::ResourceGroups::Group
  #   Properties:
  #     Name:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-
  #         - Ref: AWS::StackName
  #     ResourceQuery:
  #       Type: CLOUDFORMATION_STACK_1_0
  # ApplicationInsightsMonitoring:
  #   Type: AWS::ApplicationInsights::Application
  #   Properties:
  #     ResourceGroupName:
  #       Fn::Join:
  #       - ''
  #       - - ApplicationInsights-SAM-
  #         - Ref: AWS::StackName
  #     AutoConfigurationEnabled: 'true'
  #   DependsOn: ApplicationResourceGroup

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SlackblastApi:
    Description: API Gateway endpoint URL for Prod stage for Slackblast function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slack/events/"
  SlackblastFunction:
    Description: Slackblast Lambda Function ARN
    Value: !GetAtt SlackblastFunction.Arn
  SlackblastFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt SlackblastFunctionRole.Arn
  # S3Bucket:
  #   Description: Bucket Created using this template.
  #   Value: !Ref S3Bucket
